# Generated by Django 2.0.5 on 2018-05-24 22:24

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('For Validating', 'For Validating'), ('Validated', 'Validated'), ('Resolved', 'Resolved')], default='For Validating', max_length=20)),
                ('category', models.CharField(choices=[('CONSTRUCTION', 'planned road work'), ('SPECIAL_EVENT', 'special events (fair, sport event, etc.)'), ('INCIDENT', 'accidents and other unexpected events'), ('WEATHER_CONDITION', 'weather condition affecting the road'), ('ROAD_CONDITION', 'status of the road that might affect travellers (potholes, bad pavement, etc.)')], max_length=20)),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('author', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
